version: '3.8'

services:
  backend:
    build:
      context: ./k8s_backend
#    command: >
#      sh -c "
#      python manage.py collectstatic --no-input &&
#      python manage.py migrate &&
#      python manage.py runserver 0.0.0.0:8000
#      "
    image: gkiavash/k8s_backend
    ports:
      - "8000:8000"
    env_file:
      - k8s_backend/.env
    depends_on:
      - db

  db:
    image: postgres:13
    restart: on-failure
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: k8s_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  frontend:
    build:
      context: ./k8s_frontend
      dockerfile: Dockerfile
    image: gkiavash/k8s_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
