apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gkiavash/k8s_backend
        ports:
        - containerPort: 8000
        command:
#          - "ls"
#          - "python manage.py collectstatic --no-input"
#          - "python manage.py migrate"
          - "python manage.py runserver 0.0.0.0:8000"
        envFrom:
          - configMapRef:
              name: myconfig
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
